# Generated by Django 4.1.3 on 2022-11-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_remove_setting_image_site_alter_setting_logo_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('text', models.TextField(max_length=100)),
            ],
        ),
    ]
