# Generated by Django 4.1.3 on 2022-11-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest',
            name='text',
        ),
        migrations.AddField(
            model_name='latest',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latest',
            name='image',
            field=models.ImageField(upload_to='image_latest/'),
        ),
    ]
