# Generated by Django 4.1.3 on 2022-11-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_latest_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image/')),
                ('descreption', models.CharField(max_length=200)),
                ('name1', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='image/')),
                ('descreption1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('image2', models.ImageField(upload_to='image/')),
                ('descreption2', models.CharField(max_length=200)),
            ],
        ),
    ]
