# Generated by Django 4.1.3 on 2022-11-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_slid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slid',
            name='descreption1',
        ),
        migrations.RemoveField(
            model_name='slid',
            name='descreption2',
        ),
        migrations.RemoveField(
            model_name='slid',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='slid',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slid',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='slid',
            name='name2',
        ),
        migrations.AddField(
            model_name='slid',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
