# Generated by Django 4.1.3 on 2022-11-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_kids_man_woman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kids',
            options={'verbose_name': 'Детский', 'verbose_name_plural': 'Детский'},
        ),
    ]
