# Generated by Django 4.1.3 on 2022-11-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_alter_kids_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='man',
            options={'verbose_name': 'Мужской', 'verbose_name_plural': 'Мужской'},
        ),
        migrations.AlterModelOptions(
            name='woman',
            options={'verbose_name': 'Женский', 'verbose_name_plural': 'Женский'},
        ),
    ]
