# Generated by Django 4.1.3 on 2022-11-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_alter_man_options_alter_woman_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latest',
            options={'verbose_name': 'Электроника', 'verbose_name_plural': 'Электроника'},
        ),
    ]
