# Generated by Django 4.1.3 on 2022-11-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_alter_latest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image/')),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новинка',
            },
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
    ]
