# Generated by Django 4.1.3 on 2022-11-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_nues_alter_setting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='image1/')),
                ('image2', models.ImageField(upload_to='image2/')),
                ('image3', models.ImageField(upload_to='image3/')),
                ('image4', models.ImageField(upload_to='image4/')),
                ('image5', models.ImageField(upload_to='image5/')),
            ],
            options={
                'verbose_name': 'Инстаграм фото',
                'verbose_name_plural': 'Инстаграм фото',
            },
        ),
    ]
