# Generated by Django 4.1.3 on 2022-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_insta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='image/')),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
