# Generated by Django 4.1.3 on 2022-11-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0016_closis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closis',
            options={'verbose_name': 'Новый тавар', 'verbose_name_plural': 'Новый тавар'},
        ),
    ]
