# Generated by Django 4.1.3 on 2022-11-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0017_alter_closis_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('instagram', models.URLField()),
                ('fasebook', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='closis',
            options={'verbose_name': 'Новый тавар', 'verbose_name_plural': 'Новый '},
        ),
    ]
